version: '2'
services:
   web:
      build: .
      ports:
         - "5000:80"
      volumes:
         - /var/www:/usr/share/nginx/html
      links:
         - mongodb
   mongodb:
      image: mongo

     
